<a href="https://colab.research.google.com/github/pranjaldwivedii001-commits/Song-Recommendation-System/blob/main/Song_Recommend_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SONG RECOMMENDATION SYSTEM
https://songsuggesttt.streamlit.app/

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
song = pd.read_csv("/content/songdata.csv", on_bad_lines='skip', engine='python')

# DATA CLEANING AND INITIAL STEPS :

In [ ]:
song.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \nAnd..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \nTouch me gentl..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \nWhy I had t...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [ ]:
song = song.drop(columns=['artist','link'])

In [ ]:
song.isnull().sum()

song    0
text    0
dtype: int64

#

## 3. Feature Extraction using CountVectorizer
This section transforms the raw text data into a numerical format suitable for machine learning algorithms. We use `CountVectorizer` to create a bag-of-words representation, which is a common and effective method for converting textual data into numerical feature vectors that can be used by similarity algorithms like cosine similarity. This process helps us quantify the presence of words in each song's lyrics.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=34000, stop_words='english')

In [ ]:
song['text'] = song['text'].str.lower()

In [ ]:
song

,song,text
0,Ahe's My Kind Of Girl,"look at her face, it's a wonderful face \nand..."
1,"Andante, Andante","take it easy with me, please \ntouch me gentl..."
2,As Good As New,i'll never know why i had to go \nwhy i had t...
3,Bang,making somebody happy is a question of give an...
4,Bang-A-Boomerang,making somebody happy is a question of give an...
...,...,...
863,Heimlich Maneuver,i love you so much i need the heimlich maneuve...
864,History Is Made By Stupid People,scott became famous for freezing to death in a...
865,I Am Cow!!!!,i am cow hear me moo \ni weigh twice as much ...
866,I Pulled My Groin,i pulled my groin \nit's the very best injury...
867,Jesus' Brother Bob,if you haven't heard of me \ni wouldn't be su...

In [ ]:
song.shape

(868, 2)

In [ ]:
song['text'][0]

"look at her face, it's a wonderful face  \nand it means something special to me  \nlook at the way that she smiles when she sees me  \nhow lucky can one fellow be?  \n  \nshe's just my kind of girl, she makes me feel fine  \nwho could ever believe that she could be mine?  \nshe's just my kind of girl, without her i'm blue  \nand if she ever leaves me what could i do, what could i do?  \n  \nand when we go for a walk in the park  \nand she holds me and squeezes my hand  \nwe'll go on walking for hours and talking  \nabout all the things that we plan  \n  \nshe's just my kind of girl, she makes me feel fine  \nwho could ever believe that she could be mine?  \nshe's just my kind of girl, without her i'm blue  \nand if she ever leaves me what could i do, what could i do?\n\n"

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [ ]:
vectors = cv.fit_transform(song['text']).toarray()

In [ ]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
cv.get_feature_names_out()

array(['000', '103', '105', ..., 'yum', 'zone', 'zoo'], dtype=object)

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)

In [ ]:
import nltk

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stem(text):
  a=[]
  for i in text.split():
    a.append(ps.stem(i))

  return ' '.join(a)

In [ ]:
stem('loved to hell')

'love to hell'

In [ ]:
song['text'] = song['text'].apply(stem)

In [ ]:
song['text'][0]

"look at her face, it' a wonder face and it mean someth special to me look at the way that she smile when she see me how lucki can one fellow be? she' just my kind of girl, she make me feel fine who could ever believ that she could be mine? she' just my kind of girl, without her i'm blue and if she ever leav me what could i do, what could i do? and when we go for a walk in the park and she hold me and squeez my hand we'll go on walk for hour and talk about all the thing that we plan she' just my kind of girl, she make me feel fine who could ever believ that she could be mine? she' just my kind of girl, without her i'm blue and if she ever leav me what could i do, what could i do?"

## 5. Similarity Calculation and Recommendation System Implementation
This is the core of our recommendation system. We calculate the cosine similarity between all song lyrical vectors and implement a function to recommend songs based on a given input song.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cs = cosine_similarity(vectors)

In [ ]:
sorted(list(enumerate(cs[0],)),reverse=True,key=lambda x:x[1])[1:6]

[(34, np.float64(0.5114296826843978)),
 (92, np.float64(0.4530341419930316)),
 (411, np.float64(0.45198917872784833)),
 (274, np.float64(0.2748972773956365)),
 (231, np.float64(0.2708021147284102))]

In [ ]:
song[song['song'] =='Bang'].index[0]

np.int64(3)

In [ ]:
song.iloc[0].song

"Ahe's My Kind Of Girl"

In [ ]:
def Recommend(songs):
  song_index = song[song['song'] == songs].index[0]
  distance = cs[song_index]
  top_song = sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
  for i in top_song:
    print(song.iloc[i[0]].song)

# RESULT :

In [ ]:
Recommend('Bang-A-Boomerang')

Bang
Dum Dum Diddle
If You Love Me
I Love America
Falling In Love With Love

In [ ]:
import pickle

In [ ]:
pickle.dump(song.to_dict(),open('song.pkl','wb'))

In [ ]:
pickle.dump(cs,open('cs.pkl','wb'))